/* 
 * Ultimate Arcade Game Server API
 *
 * This exposes all APIs that are available to game servers.  All APIs that interact with a player session (aka slip), identify the player by their token that  should be passed in the `Authorization: Bearer ${TOKEN}` header' and which you should receive in the player's first message from your frontend. The fronend will get it via the Ultimate Arcade SDK. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.IO;
using Newtonsoft.Json;

namespace Arcade.UnitySDK.Server.Model
{
    /// <summary>
    /// PlayerReportScore
    /// </summary>
    public partial class PlayerReportScore 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerReportScore" /> class.
        /// </summary>
        /// <param name="score">score (required).</param>
        public PlayerReportScore(long? score = default(long?))
        {
            // to ensure "score" is required (not null)
            if (score == null)
            {
                throw new InvalidDataException("score is a required property for PlayerReportScore and cannot be null");
            }
            else
            {
                this.Score = score;
            }
        }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        [JsonProperty(PropertyName = "score")]
        public long? Score { get; set; }

    }

}
