/* 
 * Ultimate Arcade Game Server API
 *
 * This exposes all APIs that are available to game servers.  All APIs that interact with a player session (aka slip), identify the player by their token that  should be passed in the `Authorization: Bearer ${TOKEN}` header' and which you should receive in the player's first message from your frontend. The fronend will get it via the Ultimate Arcade SDK. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.IO;
using Newtonsoft.Json;

namespace Arcade.UnitySDK.Server.Model
{
    /// <summary>
    /// ServerStatus
    /// </summary>
    public partial class ServerStatus 
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServerStatus" /> class.
        /// </summary>
        /// <param name="randomSeed">randomSeed (required).</param>
        public ServerStatus(string randomSeed = default(string))
        {
            // to ensure "randomSeed" is required (not null)
            if (randomSeed == null)
            {
                throw new InvalidDataException("randomSeed is a required property for ServerStatus and cannot be null");
            }
            else
            {
                this.RandomSeed = randomSeed;
            }
        }

        /// <summary>
        /// Gets or Sets RandomSeed
        /// </summary>pool_id
        [JsonProperty(PropertyName = "random_seed")]
        public string RandomSeed { get; set; }

    }
}
